### ISSUE TITLE
failed to connect... resource name pmms... default server address...

### ISSUE THREAD

**Issue by ccking91** [kibook/pmms#10]
already read this [Failed to connect to xxx #3](https://github.com/kibook/pmms/issues/3)...

thanks first...
resource name pmms...
default server address...
still failed to connect...
need help...

**Comment by kibook** [comment]
Do you have any issues connecting to the default server URL in your web browser? Try going here: https://kibook.github.io/pmms. You should get a black page.

I have an alternative server you can try to rule out it being an issue just with the GitHub Pages website: https://fivem.khzae.net/pmms. Try using that instead and let me know if you get the same issue.

Have you changed anything at all in [config.lua](https://github.com/kibook/pmms/blob/master/config.lua)? Or is everything default? If you changed anything, could you attach it to this issue?

Are you using the latest commit or an older one? The last major change to the DUI server was about 8 days ago (be86c0f916a279ed2c064ca3c42f385027d28d43), so if you're using a commit older than that, you might have issues with the default server. If you can let me know which commit you're using, I can test it out on that commit myself.

**Comment by ccking91** [comment]
download latest today and all default...
use web browser can connect to two address...
[https://kibook.github.io/pmms](https://kibook.github.io/pmms)
[https://fivem.khzae.net/pmms](https://fivem.khzae.net/pmms)
i have try host [gh-pages](https://github.com/kibook/pmms/tree/gh-pages) on my pc...
same problem...

**Comment by kibook** [comment]
I should update the little blurb about hosting your own server in [config.lua](https://github.com/kibook/pmms/blob/2baa6f44bfde12f3983a5c8625454f5004fb3f5b/config.lua#L695), as that expects you to have your own web server. It's actually much simpler to just fork this repository on GitHub. When you fork it, you should get your own copy of the GitHub Pages website, at `https://<your username>.github.io/pmms`.

However, if neither the default server nor the alternative are working, I wouldn't expect your own to work either.

I didn't ask, but is this for FiveM or RedM? If it's on RedM, then the issue is a lot more obvious since RedM shouldn't be using the DUI server in the first place.

For FiveM, I am not able to replicate this issue.

**Comment by ccking91** [comment]
im use fivem...
after edit like this can play...
![Capture](https://user-images.githubusercontent.com/87742755/126500262-f5fb9ecf-ee34-402a-beb7-26976919e21b.PNG)
thanks for reply...

**Comment by kibook** [comment]
That's very interesting. The reason why `DuiBrowser:waitForConnection` was added in the first place was to make sure the DUI browser had fully connected before trying to use it, otherwise I would sometimes have to click the play button multiple times before something would play. Do you get similar behaviour?

If you can play things, that means other messages are being passed from the DUI browser successfully, but somehow `DuiBrowser:init` or `DuiBrowser:initDone` is failing to be passed, or at least it's taking longer than 5 seconds.

Does it also work if you increase the `5000` to a higher number? Say `10000` (10 seconds)? Or even `30000` (30 seconds)?

What I can do maybe is similar to what you've done by commenting out those lines, wait for a certain period of time but then finalize it anyway even if it fails to detect the connection.

**Comment by ccking91** [comment]
working now...
change `timeWaited` to `30000`...
and try 3 time...
every time between 12000-13000...

**Comment by kibook** [comment]
12-13 seconds to connect to the website seems extreme to me, but obviously it depends on connection speeds.

7b1dd0a and 0bad793 added some improvements to `waitForConnection`, mainly the timeout being configurable and raised to 30 seconds by default.

**Comment by ccking91** [comment]
thanks for amazing script...
