### ISSUE TITLE
Other player's played URL show up for everyone.

### ISSUE THREAD

**Issue by Kurosar** [kibook/pmms#11]
I don't know if it's a bug or feature, but if another player puts something on pmms, I can see what they put up there, and they can see what I put on my pmms screen, anyone can also remove/stop played url's serverwide.

![image](https://user-images.githubusercontent.com/4887819/126899601-ff949b4d-a4ab-4cf8-a2b8-e3481462cd97.png)

**Comment by kibook** [comment]
By default, normal players can interact with any nearby media player. Managers (players with the `pmms.manage` ace, which by default includes the `group.admin` principal) can see any active media player serverwide, as well as do things like lock media players so normal players cannot control them.

A normal player would not be able to see media player "125" in the example above, as it's not nearby (in fact, the corresponding entity doesn't even exist atm, hence the `-` for distance). However, since you are a manager, you can.

If you simply want only admins to be able to play and control stuff with pmms, you can grant the `pmms.interact` only to admins instead of all players. Change the following line in permissions.cfg:
```
add_ace builtin.everyone pmms.interact allow
```
to:
```
add_ace group.admin pmms.interact allow
```

If you want to go a step further, and restrict certain entities to certain players, for example a TV to the "owner" of a property, you can not grant the `pmms.anyEntity` ace, which allows players to play things on any valid entity, and take advantage of the `enableEntity`/`disableEntity` or `createMediaPlayer`/`deleteMediaPlayer` exports.

**Example 1**: a player owns a house, and in that house is a TV object. In the property management resource, when the owner enters their home, it executes `exports.pmms:enableEntity(tvEntity)` where `tvEntity` is the entity ID of the TV object, allowing the owner (and only the owner) to control that TV. When they leave, `exports.pmms:disableEntity(tvEntity)` is executed to clean up.

**Example 2**: a player does a command like /boombox. That commands executes:
```lua
local boomboxEntity = exports.pmms:createMediaPlayer{model = `prop_boombox_01`, position = playerPos}
```
which creates a new boombox object and automatically adds it to the list of entities the player can control in pmms, and returns its entity ID. The command then attaches the boombox to the player. When they do /boombox again, it executes `exports.pmms:deleteMediaPlayer(boomboxEntity)` to stop whatever was playing on the boombox and delete the entity.

I mainly play on freeroam/sandbox-type servers without things like property ownership, so the defaults are more suited for that kind of server and I haven't implemented anything like I've described using those exports myself. If you come across any issues using these exports, let me know.

**Comment by Kurosar** [comment]
This was a super helpful explanation, thanks a lot !

PS : We all love PMMS on the server, since I installed it, everyone uses it and absolutely LOVE it ! Congratulations.
