### ISSUE TITLE
URL Input

### ISSUE THREAD

**Issue by nicxes** [kibook/pmms#14]
I can't see the input to put the URL. Maybe is a limitation of scaleforms?

![image](https://user-images.githubusercontent.com/8798356/134338010-1fa781e0-6131-4ed1-94d3-f964d179d544.png)

**Comment by TayMcKenzieNZ** [comment]
Have you set up the ace permission?

**Comment by kibook** [comment]
As @TayMcKenzieNZ says, the permissions are probably not configured. In order to use a custom URL, a player needs at least the `pmms.customUrl` ace. The default [permissions.cfg](https://github.com/kibook/pmms/blob/master/permissions.cfg) allows `group.admin` to do everything, and everyone else can only play preset media and not custom URLs.

Make sure in server.cfg, before `start pmms` or `ensure pmms`, you've also placed `exec resources/[local]/pmms/permissions.cfg` (adjust the path to where you have installed pmms).

The tooltip probably shouldn't appear if the URL field is disabled, so I'll look into that.

**Comment by kibook** [comment]
The tooltip about the URL field will no longer appear when URL field is hidden as of 184a339.

**Comment by nicxes** [comment]
Oh my bad! I forget to open the steam client.. Thanks!
