### ISSUE TITLE
Error playing MP4 from my home server

### ISSUE THREAD

**Issue by MrMallenby** [kibook/pmms#20]
Im using a map that has a home cinema built in and im trying to set it up pmms so that i can play videos from my home server, be it movies nights or what have you however im running into the error shown here
![FiveM_b2372_GTAProcess_cWD0IyhUDh](https://user-images.githubusercontent.com/4685327/140181067-957560f7-5a83-4eee-ba6a-e14e19475a36.png)
e

**Comment by kibook** [comment]
pmms uses an HTTPS webpage for DUI by default, https://kibook.github.io/pmms. The web browser used for NUI does not allow requesting unsecured content (plain HTTP) from a secure (HTTPS) site, which is what it means by "mixed content". Instead, it tries to "upgrade" the http:// URL to https:// automatically. If your home server isn't configured to accept https:// requests, then you'll get this error.

See #4, it's the same issue.

A solution is to use a plain HTTP site for DUI instead of the current default. Web browsers usually don't allow an HTTPS site to request HTTP content due to it being a security risk, but an HTTP site requesting HTTPS content is fine. If you want to do this with your home server, clone the `gh-pages` branch of this repository and install it in your HTTP server:
```
git clone -b gh-pages https://github.com/kibook/pmms
```
Then change `Config.dui.url` in config.lua to the appropriate URL, such as `http://home.mallenby.co.uk/pmms`.

Another solution, and one that I'm looking at maybe integrating into pmms by default, is to use the HTTP server that is built in to FXServer. Resources can respond to HTTP requests using the `SetHttpHandler` function. I have another resource, [httpmanager](https://github.com/kibook/httpmanager), which can make this easier. If I do make this part of pmms by default, httpmanager will become a dependency that you'll need to install with it.

**Comment by MrMallenby** [comment]
Ahhh ok that makes alot of sense, thank you for such a detailed response. Will deffo have to do some testing and such

**Comment by kibook** [comment]
297add6 switches pmms to use the HTTP server built in to FXServer for DUI instead of the external github.io page, which fixes the issue playing plain HTTP URLs.

**Comment by MrMallenby** [comment]
Mate your a legend will give it a crack tomorrow

**Comment by MrMallenby** [comment]
Confirmed working a treat bud
![20211105163320_1](https://user-images.githubusercontent.com/4685327/140545754-2ea94cc3-7032-410a-a2da-f6bfaf2c47bd.jpg)

**Comment by MrMallenby** [comment]
Ok i have noticed an issue however and im not sure if its script wise or what but after making the switch to the new version artists that worked on the old version no longer work, examples being "in this moment", "meatloaf" and "motionless in white" when played from youtube. Comes up with an error about the song being unavailable and view on youtub
![20211105212713_1](https://user-images.githubusercontent.com/4685327/140580549-91318c82-bf54-4a17-b55d-8a60a3497abe.jpg)
e

**Comment by kibook** [comment]
Some videos may not work because YouTube or the uploader have disabled the ability to embed them on another website, which is essentially what pmms is doing. It can also be blocked due to age or geographical restrictions, though those usually have specific error messages to indicate which is happening.

If you have some specific examples of videos where this happens, feel free to include them in a new issue, and I can maybe test them myself to find out more on why they're blocked.
