### ISSUE TITLE
Add examples 

### ISSUE THREAD

**Issue by dolutattoo** [kibook/pmms#22]
It could be great to add some examples, expetially for scaleforms.
I am trying to start a video from a non-admin client, without using server exports, but cannot get it to work :(

**Comment by kibook** [comment]
There are some [video examples](https://github.com/kibook/pmms#examples), but maybe I can add some textual, step-by-step ones for certain things.

What seems to trip a lot of people up is that in order to allow non-admin players to play custom URLs like YouTube ones, [you must modify the default permissions](https://github.com/kibook/pmms#permissions). This is intentional, though, as allowing custom URLs presents some risks in terms of the appropriateness of what is being played and, if any custom URL is allowed, a security risk that can cause private info, such as a player's IP address, to be leaked. Out of the box, non-admin players are restricted to only being able to play specific media you have approved by adding it to `Config.presets`.
