### ISSUE TITLE
Question about YouTube Links with the script

### ISSUE THREAD

**Issue by BraddersB** [kibook/pmms#25]
Hey guys,

I've added the script to my server, but I was wondering if there is a certain restriction wo what links work video wise, as it seems very limited to what can be played with a lot of videos, most of them come up with the "Video Unavailable" "View On YouTube" on the screen. It's a bit annoying, but if you have idea, I would love to know.

Cheers,
Bradders.
![20211204013937_1](https://user-images.githubusercontent.com/73504086/144692141-41344f60-92ab-4128-8355-91b5e1afd1cc.jpg)

**Comment by kibook** [comment]
Could you include some examples of videos that are blocked for you?

YouTube will block videos for a variety reasons. Some videos will have embedding disabled, which is essentially what this resource does, embeds the YouTube video in another web page, the one being displayed on the TV via DUI. YouTube can also be picky about the type of page the video is being embedded on, for example if that page is unsecured (plain HTTP instead of HTTPS), more videos tend to get blocked.

There were some fairly recent changes that affected this, so make sure you're using the latest version. If you can provide some example videos, I can test them myself and possibly get more details on why they're being blocked and whether anything can be done about it.

**Comment by TayMcKenzieNZ** [comment]
What's also weird is, you could have two video URLs, same video, but uploaded by two different people, first video will say age restricted or must watch on YouTube to view it, second video will play fine.

Then there's regional geo-blocking, but that can also weirdly be bypassed by watching it on a URL uploaded by someone else 🤔🤷🏻‍♂️

**Comment by kibook** [comment]
> What's also weird is, you could have two video URLs, same video, but uploaded by two different people, first video will say age restricted or must watch on YouTube to view it, second video will play fine.

It doesn't really surprise me that they can end up being tagged differently by YouTube's automatic systems. It may be that one has been reviewed by a human and tagged as requiring age or geographical restrictions, while the other has yet to be seen by any human reviewers and so remains unrestricted for the time being.

I've closed this issue for now since without any examples of videos that are not playing despite not being age- or geo-restricted (just simply showing "Video unavailable" like in the original screenshot), there's nothing I can do. If anyone has any examples, feel free to re-open it.
