### ISSUE TITLE
Failed to connect to xxx

### ISSUE THREAD

**Issue by Sakarias411** [kibook/pmms#3]
Hello,

Well, first, that's a fantastic project ! 
Then, I've tried to install it, but when I play something, it says this in the console : 
![image](https://user-images.githubusercontent.com/4887819/125177814-33ec1a80-e1df-11eb-82e2-31bd42705c6d.png)

I even tried to clone the gh-pages branch and hosted it on my server, and it's still not working, any idea ?

Best regards.

**Comment by kibook** [comment]
The default server address is https://kibook.github.io/pmms and not https://github.com/kibook/pmms. Try putting it back to the default and see if that works.

It's not strictly necessary to host your own server, I think most people would be fine with the default. One reason to do so at this point might be because this project is pretty early in development, and so stuff is likely to change with the DUI server which may break things if you're not also updating the resource right away. If you do want to host your own server, make sure to point to the GitHub Pages environment that is created and not the GitHub repository. It should be `https://<your username>.github.io/pmms`.

**Comment by Sakarias411** [comment]
Thanks for your fast response,
Haha, now I have a different error : 
![image](https://user-images.githubusercontent.com/4887819/125178040-436c6300-e1e1-11eb-9b70-b8fba6c779ed.png)

**Comment by kibook** [comment]
I'm not sure about what would cause those errors from NUI, but just to check, did you rename the resource from `pmms` to something else? Currently it has to be named `pmms` in order for it to work. I might try and make it more flexible regarding that, but if not I will definitely add something in the README about the name.

**Comment by Sakarias411** [comment]
Ha... Yes I renamed my resource pmms-media.
I changed it back to pmms and it's working now !! 

Maybe you can add a little note on the main github page about that ?

![image](https://user-images.githubusercontent.com/4887819/125178668-5c781280-e1e7-11eb-96ee-4d57f9491f75.png)

Congratz on the script !

**Comment by kibook** [comment]
Absolutely, although I think I can instead make it so the name isn't hardcoded in the DUI server code. I'm going test that now, if for some reason it turns out not to work, I'll update the README to point out that the resource can't be renamed.

**Comment by ccking91** [comment]
thanks first...
resource name pmms...
default server address...
still failed to connect...
need help...
