### ISSUE TITLE
can't put URL

### ISSUE THREAD

**Issue by parham-tehrani** [kibook/pmms#37]
the bar to paste the URL doesn't show up and it says no nearby media players
![image](https://user-images.githubusercontent.com/96952367/158020105-db4e9570-45b4-4861-b4a3-46babf1a4042.png)

**Comment by kibook** [comment]
It seems like the permissions aren't set up. Make sure you've done every step in the [Installing](https://github.com/kibook/pmms#installing) section of the README, particularly step 3.

**Comment by parham-tehrani** [comment]
i had followed the instruction and removed all the permission's limits so that everyone could do it...still couldn't make it work ... :( i'll remove everything and re add them all...will keep you posted :) thank you for the response !

**Comment by kibook** [comment]
If you made changes to permissions.cfg, could you post what yours contains so I can see if the problem lies there?

You can also confirm whether the permissions have actually been loaded or not by using the `list_aces` command in the server console (not the in-game console that appears with F8). Look for lines matching the ones in permissions.cfg. If they are not present, then permissions.cfg was probably not executed.

The permissions out of the box do allow everyone to use pmms, they only restrict players not in `group.admin` to using URLs from "allowed" sites only, the default being YouTube and Twitch. You generally don't want to grant *everyone* permissions like `pmms.manage`, as that is meant for an admin user and will allow players to see and control active media players from anywhere on the map, not just those nearby.

**Comment by parham-tehrani** [comment]
![image](https://user-images.githubusercontent.com/96952367/158395640-f9835eb1-69cb-4046-af21-abd002fa729c.png)

so this is the config file, i added the http manager, then i added the pmms, started it as well...

**Comment by parham-tehrani** [comment]
aight it worked...idk how, restarted the pmms couple of times and it worked ! :D THANK YOUUUUU

**Comment by kibook** [comment]
Glad it's working! You might want to try it with the default permissions.cfg now as well, because that should have also worked and may make more sense, especially on a public server. `pmms.manage` in particular is normally reserved for admin users, which is why that line giving it to `builtin.everyone` (which means *all* players) is commented out by default. It means all players will be able to see and control every active media player across the whole map, instead of just the ones close by to them, which could be confusing.

**Comment by parham-tehrani** [comment]
is it possible to make it job specific ?!

**Comment by parham-tehrani** [comment]
how does the lock work ?! and is it possible to add new objects as players?!

**Comment by rhapidfyre** [comment]
For anyone else coming across this ticket later, I had a similar issue.

Be sure to read the documentation. You need to set up a renderer before trying to play anything.. So if the URL box is missing or it won't let you click in it, create a render screen first.
