### ISSUE TITLE
perms and url not working 

### ISSUE THREAD

**Issue by tyler4435** [kibook/pmms#48]
perms do not work and it wont let me put a url in to play something

**Comment by tyler4435** [comment]
and i have been working on it for hours straight

**Comment by TayMcKenzieNZ** [comment]
You need to download this

https://github.com/kibook/httpmanager

Then you need to place the files from PMMS repository in a new folder in your resources directory.

Example: resources/[local]/pmms

NOTE

The name of the resource must be in all lowercase in order for it to function properly. This is due to how NUI callbacks work.

Add the following in your server.cfg:

exec @pmms/permissions.cfg
start pmms

pmms has it's own permissions and is to set to admin by default.

You can read all this important information in the ReadMe of this repository....
