### ISSUE TITLE
Local MP4 file viewing not working

### ISSUE THREAD

**Issue by lvto2000** [kibook/pmms#54]
I have gotten this to successfully work with YouTube links.  I cannot get it to work with local files stored in the pmms resource folder area.  The errors I get span from incorrect media format to DUI timeouts after resetting the graphical interface for pmms.  The DUI timeouts are interesting.  I am puzzled why it is saying the following link is timing out instead of the /media directory.   

**Here is the DUI timeout error:**
Failed to initialize DUI browser: Could not connect to http://[MY IP]:30120/pmms/dui/  within 30000 milliseconds

By the way, this happens when I use the graphical pmms admin tool and using the chat command pmms_play.  I also get the media error too when using pmms_play.  

**Assume the following:**

1. The file is stored in the **pmms/html/media** directory
2. The **pmms** application has a lower case resource directory name is in the right resources directory 
3. It runs/stops/starts fine
4. The **httmanager** resource is in the same directory as the **pmms**.
5. The MP4 file size is 275mb
6. YouTube videos work perfectly 
7. Viewing the MP4 file using **http://[MY IP]:30120/pmms/media/[mp4filename.mp4]** and my chrome browser works perfectly

Any ideas?

**Comment by kibook** [comment]
Is the **dui** folder inside the **http** directory empty? If you downloaded this from GitHub rather than cloning it via git, or cloned it without the `--recurse-submodules` option, then you won't have gotten the necessary files.

The **dui** folder is actually a submodule that points to this repository: https://github.com/kibook/pmms-dui. Unfortunately it looks like GitHub doesn't copy the contents of submodules when you download using the "Download ZIP" option for example. You can fix this by downloading and placing the contents of that repository into the **dui** folder.

**Comment by lvto2000** [comment]
> Is the **dui** folder inside the **http** directory empty? If you downloaded this from GitHub rather than cloning it via git, or cloned it without the `--recurse-submodules` option, then you won't have gotten the necessary files.
> 
> The **dui** folder is actually a submodule that points to this repository: https://github.com/kibook/pmms-dui. Unfortunately it looks like GitHub doesn't copy the contents of submodules when you download using the "Download ZIP" option for example. You can fix this by downloading and placing the contents of that repository into the **dui** folder.

Thank you!  I will try this and get back to you with success or failure update.

**Comment by lvto2000** [comment]
That worked!  I guess I missed that part in the documentation.  Thank you again and appreciate the quick response!!!
